### PR TITLE
deb: support SHA1 and SHA256 checksums

### LINKED ISSUE #59: MD5 sum used for package signing is too weak for Ubuntu Xenial
Ubuntu 16.04 does not work with the Packages files generated by `prm`. It appears the hashing function (MD5) is too weak. The following error is provided on `apt-get update`:

    W: Failed to fetch https://my.repo.url/dists/xenial/Release  No Hash entry in Release file /var/lib/apt/lists/partial/my_repo_url_dists_xenial_Release, which is considered strong enough for security purposes

### PR DESCRIPTION
**Pull request by jgoldschrafe**
Adds support for SHA1 and SHA256 checksums to Release and Packages files.

My .vimrc automatically trimmed trailing whitespace from a few unrelated lines. I can manually fix if it's a problem.

Closes #59.

### CODE REVIEW

File: lib/prm/repo.rb [hunk 1]
```diff
@@ -194,8 +202,6 @@ def generate_release_gpg(path,release,gpg)
         Dir.chdir("#{path}/dists/#{release}") do
             if gpg.nil?
               sign_cmd = "gpg --yes --output Release.gpg -b Release"
-            elsif !gpg_passphrase.nil?
-              sign_cmd = "echo \'#{gpg_passphrase}\' | gpg -u #{gpg} --passphrase-fd 0 --yes --output Release.gpg -b Release"
```
Comment (SpikesDivZero) [inline lib/prm/repo.rb]: I had a similar problem with hashing algos, and so I pulled this patch down for my own use -- in testing it, I noticed that gpg_passphrase support no longer works. Was this removal intentional? (If it's got issues, I've no issues with possibly adjusting my workflow, just hoping to understand the context.)

Comment (jgoldschrafe) [inline lib/prm/repo.rb]: Rebase boo-boo. Nice catch! Fixed in updated commit.

**Comment by mschwager** [comment]
Thanks for adding this PR! I'm seeing this issue as well.

Any chance we can future proof it a bit and add `SHA512` support as well?

**Comment by dnbert** [comment]
Sorry for the super late reply, merging!

**Comment by mschwager** [comment]
He's alive! :)

Thanks again @dnbert!
